version: "3"
services:
  api:
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/github.com/luuminhthai/rest-api-golang/api
    # depends_on:
    #   - db
    environment:
      - DB_NAME=rest-api-golang
      - DB_HOSTNAME=localhost:27018

  # db:
  #   image: mongo:3.4
  #   restart: always
  #   container_name: rest-api-golang-db
  #   ports:
  #     - "27018:27018"
  #   volumes:
  #     - ./backup:/backup:rw
    